// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvLJc8XTyK7yDyBVQQT3DpG9MD_YGQBZo',
    appId: '1:539641723184:web:1137a84b5eb6bc8554b0f5',
    messagingSenderId: '539641723184',
    projectId: 'coba1-5f863',
    authDomain: 'coba1-5f863.firebaseapp.com',
    databaseURL: 'https://coba1-5f863-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coba1-5f863.firebasestorage.app',
    measurementId: 'G-NSKZMW33R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8k8-F3yZB8Zrhq0lGw3v620qPBpvSa7Y',
    appId: '1:539641723184:android:5a40ba15d6529a3154b0f5',
    messagingSenderId: '539641723184',
    projectId: 'coba1-5f863',
    databaseURL: 'https://coba1-5f863-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coba1-5f863.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvLJc8XTyK7yDyBVQQT3DpG9MD_YGQBZo',
    appId: '1:539641723184:web:e1513f15f652aa2254b0f5',
    messagingSenderId: '539641723184',
    projectId: 'coba1-5f863',
    authDomain: 'coba1-5f863.firebaseapp.com',
    databaseURL: 'https://coba1-5f863-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coba1-5f863.firebasestorage.app',
    measurementId: 'G-6YG6K2LF6W',
  );
}
